### ISSUE TITLE
copy operation in progress

### ISSUE THREAD

**Issue by christopherhesse** [hauntsaninja/boostedblob#13]
Should `bbb` by default wait for existing copy operations to finish?  It prints the abort command currently but it's slightly annoying to deal with.

**Comment by hauntsaninja** [comment]
Yes, I think it's important for bbb to wait for copies to complete, since it's highly nonintuitive for users if a cp command succeeds, but the blobs aren't actually copied over yet. 

bbb only prints the abort command only if an exception is received while waiting for the copy to complete (notably, KeyboardInterrupt). In theory maybe we could issue the cancels ourselves, but in practice that's a little hard since the Python interpreter is shutting down.

**Comment by hauntsaninja** [comment]
To be clear, waiting for copies to complete is the expected current behaviour. Are you seeing something different?

**Comment by christopherhesse** [comment]
Yeah, let me update to see if I'm using an old version.

**Comment by christopherhesse** [comment]
I can reproduce the issue reliably with the latest boostedblob.

```
bbb cptree <path1> <path2>
ctrl-c
bbb cptree <path1> <path2>
```

The command fails immediately with:

```
[boostedblob] Asynchronous cloud copy operation is still pending. You can cancel the copy manually with `az storage blob copy cancel --copy-id <redacted> --destination-blob <redacted> --destination-container <redacted> --account-name <redacted>`. Note if successfully cancelled, this will produce an empty blob at the destination.
ERROR: RequestFailure: Reason: 'There is currently a pending copy operation.'
Request: Request(method='PUT', url='<redacted>', params={})
Status: 409
```

**Comment by hauntsaninja** [comment]
Yeah, Azure only lets you do one copy at a time. I guess the second `bbb cptree` could endlessly retry 409s, but I feel like that may lead to surprising results.

In any case, this should all be moot since we no longer use "Copy Blob" between storage accounts, instead doing something complicated involving "Put Block from URL"
