### ISSUE TITLE
Possible issue with long running requests 

### ISSUE THREAD

**Issue by christopherhesse** [hauntsaninja/boostedblob#14]
I ran `bbb ls <directory with many files>`.  After an hour it failed with:

```
ERROR: RequestFailure: Reason: 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
Request: Request(method='GET', url='<redacted>', params={'comp': 'list', 'restype': 'container', 'prefix': '<redacted>', 'delimiter': '/', 'marker': '<redacted>'})
Status: 403
```

**Comment by christopherhesse** [comment]
Could be because my laptop went to sleep or because it took so long, the command ran for 1 hour and 6 minutes

**Comment by hauntsaninja** [comment]
So there's one bug I've been aware of since the beginning of boostedblob, where if a single request is retried for somewhere between an hour to five minutes (depending on length of program and luck), you can run into a 403, since we don't reauth requests on retry.

In practice, I've only seen this happen once, under somewhat exceptional circumstances.

(Note that `bbb ls` does many requests because of paging. bbb does reauth the request for each page https://github.com/hauntsaninja/boostedblob/blob/9c85757980983ee5fe1bd56d8eeac8e64b0be7c0/boostedblob/request.py#L261 , the known bug is really just about retrying the exact same request)

**Comment by christopherhesse** [comment]
The build_req functions are pretty annoying (probably should be like some object that you pass in with some interface)., probably fine to mark this WONTFIX if this never happens in practice (this is the only time I have observed this).  I'll run the command one more time to see what happens.
